# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01252ae4c049a197212f44ab90b64fcf083a75b9fc9f7799660b2fb0e07b98812f5b6347b3f5e9215247cace8da336cb1ed3ad6d422b66d7dedd63cea9dc0815

test:
  secret_key_base: 689752b664c081eda3f056109741dfc83eb30eeb56f7e013380e0d2593dab16c03ca14cfa63c72a5b31a72d80aa9770992bde1116941f42b7ee1b706da16abc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
